version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    build: nginx
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - .env
    environment:
        HOST: $HOST
        EMAIL: $EMAIL
    depends_on:
      - server
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./certs:$CERTS

  server:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

    restart: unless-stopped

    build: server
    container_name: server
    env_file:
      - .env
    tty: true
    user: 1000:1000
    ports:
      - "5001:5000"
    environment:
      DEBUG: "true"
      HOST: $HOST
      SYSTEM: /system
      PYTHONIOENCODING: utf-8
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - "$SYSTEM:/system"
      - "./server:/flask_app"
  service:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
       context: service
       args:
         SYSTEM: /system

    restart: unless-stopped

    container_name: service
    env_file:
      - .env
    tty: true
    user: 1000:1000
    ports:
      - "5000:5000"
    environment:
      DEBUG: "true"
      HOST: $HOST
      SYSTEM: /system
      PYTHONIOENCODING: utf-8
      HAYSTACK_TELEMETRY_ENABLED: "False"
      HF_HUB_DISABLE_TELEMETRY: True
      DISABLE_TELEMETRY: True
    volumes:
      - "$SYSTEM:/system"
      - "./service:/flask_app"
      - "./lib:/flask_app/lib"

      - "./.cache-cr:/chroma:rw"
      - "./.cache-hf:/.cache:rw"



  philospher:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build: philosopher
    container_name: philosopher
    env_file:
      - .env
    tty: true
    user: 1000:1000
    environment:
      DEBUG: "true"
      HOST: $HOST
      SYSTEM: /system
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - "$SYSTEM:/system"

  web:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: web
      target:  $TARGET
    container_name: web
    volumes:
      - ./web/src:/app/src
    tty: true
    env_file:
      - .env



