defaults: &defaults
  embedding_dim: 1024
  batch_size: 8
  n_epochs: 10000
  stop_f1_score: 0.93
  weight_decay: 0.0001
  batches_per_epoch: 17

# ONE MODEL PER TASK
# decide:
#   - is a subclass-set of class
#   - which is subclass of which
#   - is dialectical triple
#   - which is thesis, antithesis, synthesis

# We speak of model classes in the way, we need models for conmparing n samples
# varying from 4 to 10.


# This model class determines the "dialectical role" of three concepts compared
# to each other and some additional samples. It selects the "good" ones and
# assigns labels for "thesis", "antithesis" and "synthesis".
tas_selector: &tas_selector
  <<: *defaults
  n_classes: 4
  classes:
    - labels
    - valid
    - random
  probs:
    - 0.05
    - 0.6
    - 0.35
  lr: 0.001
  embedding_model: BAAI/bge-large-en-v1.5


#   - which is thesis, antithesis, synthesis
tas_selector_only: &tas_selector_only
  <<: *tas_selector
  n_classes: 4
  classes:
    - labels
    - valid
  probs:
    - 0.05
    - 0.95
  lr: 0.00003
  embedding_model: BAAI/bge-large-en-v1.5

# This model class is concerned if one concept is a class of other concepts.
# The model selects, which one might be the class for maximum 3 others.
# The model also decides, if the concept is not a class of any other.
hie_selector: &hie_selector
  <<: *defaults
  n_classes: 5
  classes:
    - labels_hie
    - valid_hie
    #- random_hie
    #- random
  probs:
    - 0.05
    - 0.95
    #- 0.45
    #- 0.0
  lr: 0.003
  #embedding_model: BAAI/bge-large-en-v1.5

  embedding_model: legacy107/multi-qa-mpnet-base-dot-v1-wikipedia-search
  embedding_dim: 768

models:
  tas_4_only:
    <<: *tas_selector_only
    n_samples:
      4

  hierarchical:
    <<: *hie_selector
    n_samples: 5

  tas_4:
    <<: *tas_selector
    n_samples: 4
  tas_5:
    <<: *tas_selector
    n_samples: 5





