apiVersion: v1
data:
  fullchain.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFMDCCAxigAwIBAgIUT/sj6Xd8EAtBJmia8wzargp8fJUwDQYJKoZIhvcNAQEL
    BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI2MDUxMTA5NTg0OFoXDTI3MDUx
    MTA5NTg0OFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIICIjANBgkqhkiG9w0BAQEF
    AAOCAg8AMIICCgKCAgEA5j4GfNpTE9uhLLP+PAMRzXfc8m46tASaRc/+ZaueTJKv
    r3nae2caO6QSjgxYWyEyjn4eMQOVQMTWcOBR9+bVXleVIhhgbQpxuBD0Qu2ba7Cy
    zKP58a+BimNbRpFkRp1QNbgtKZ4DGofw10kUFPQNjB/H03HWwSbLUvIgrqBBww65
    T66q4lY+kYt/kxuvcjshSs8nB3HbAcqjRoU0Um3eD/nrN3VxUYiuWjtto2FGEEnU
    3yjQ8XtIqmtBeH+LWPRuW2aRNSxohM6Y0GjGGSfvDYJ8jkyVLfEWCJB/W4WMsDwF
    IZdVQvQc4jiHAPSzdMdp3tj0YOLxLiqwlqY+T0FNZfQJapnRKWPLJPFibJUDQVuJ
    R74Va60264hDdWrYNT8jAxjvVlydnVmjUQGZN4YKaf3E7tuKFAc+OFHUCEG+21SV
    yq/rN7pyno36u//7LMAoAYYGN/OFM+jpM/vqNeN0+0KwdeVl2F44JuZqQxJmuyqy
    GJJnoN0+6tifF/I7PMp7I+f2ebpqPHJBV5z8ibZpvOURQKcGH7yU9t22kHOIlKPQ
    ZLUe0vgcZVaPHlRB877Ym5UWfKSsfAXJgZkBRdM4QCJRXaQClJNH63yfTtSAFWdS
    iriggYeoYRWv1oP7G5eQ8TJBXMO6cO5wcJUg05cj5uQjDolInEh1ekpQEFPWua0C
    AwEAAaN6MHgwHQYDVR0OBBYEFLyJbOgCJIrzt9DqvMCVao+krOmQMB8GA1UdIwQY
    MBaAFLyJbOgCJIrzt9DqvMCVao+krOmQMA8GA1UdEwEB/wQFMAMBAf8wJQYDVR0R
    BB4wHIIJbG9jYWxob3N0gglsb2NhbGhvc3SHBH8AAAEwDQYJKoZIhvcNAQELBQAD
    ggIBADPqPBx3KtBPA++Nfz4hd8EIrO4yadSofMKcL7u9vENyS4wLuacvjSwFJxP8
    PjNuUdm01VlpCw8lgDPFT+L4Et18OVQfBuClxjhb4hX12bbhy9r884yBT9qWQZ6+
    iHYPvef4/+gG95w4zvigB39lSrD8JuQAoGySUIqZdiPTGotTxjh/laxt3vE62WOE
    4bpU2j998C7WE1BSRIIjAlsvJeZYYDakGr0Xr6sw7cczYH7Q1NcaiPPJ2UmBpd6p
    +30yXy2qaXFa5YpqBIX27hxFdAXhAkxWvTBlT7APrQSLc6Dfrud0we4L13wMjyw1
    OPtRPpxA50Ytf2RcQ0PuGerLQsCYvTFtHuYwCahWjS5cyLEP+GIjRl7AHJKv87KS
    nbMT9tLofSbYQ1BxV6EBQ2WInxXcb484wDpTD8sgRhNX9QAT+7s9ZEnKZ6N523A7
    pSvfsRYssurqXeW7TmjyWunnpImZTee7TukkhQN55COfLRLJG3J8bLBr4UJ1qrje
    7GqvYp876Svon34mGqo335/dlkOMj6NnfGnFhk88iW8cKiIiCvpypPyTgKYB+Bcn
    z0jzd3aJwSSmjHqPs/XcYFhc5mzNzRviLmUmFjfcooa6D6x5YRMOeLzIkG+igLCA
    pU5bRewUxYSnyh9vBH31xvkS1pLBI1h8S1kUJEUnIPAXpTMJ
    -----END CERTIFICATE-----
  privkey.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDmPgZ82lMT26Es
    s/48AxHNd9zybjq0BJpFz/5lq55Mkq+vedp7Zxo7pBKODFhbITKOfh4xA5VAxNZw
    4FH35tVeV5UiGGBtCnG4EPRC7ZtrsLLMo/nxr4GKY1tGkWRGnVA1uC0pngMah/DX
    SRQU9A2MH8fTcdbBJstS8iCuoEHDDrlPrqriVj6Ri3+TG69yOyFKzycHcdsByqNG
    hTRSbd4P+es3dXFRiK5aO22jYUYQSdTfKNDxe0iqa0F4f4tY9G5bZpE1LGiEzpjQ
    aMYZJ+8NgnyOTJUt8RYIkH9bhYywPAUhl1VC9BziOIcA9LN0x2ne2PRg4vEuKrCW
    pj5PQU1l9AlqmdEpY8sk8WJslQNBW4lHvhVrrTbriEN1atg1PyMDGO9WXJ2dWaNR
    AZk3hgpp/cTu24oUBz44UdQIQb7bVJXKr+s3unKejfq7//sswCgBhgY384Uz6Okz
    ++o143T7QrB15WXYXjgm5mpDEma7KrIYkmeg3T7q2J8X8js8ynsj5/Z5umo8ckFX
    nPyJtmm85RFApwYfvJT23baQc4iUo9BktR7S+BxlVo8eVEHzvtiblRZ8pKx8BcmB
    mQFF0zhAIlFdpAKUk0frfJ9O1IAVZ1KKuKCBh6hhFa/Wg/sbl5DxMkFcw7pw7nBw
    lSDTlyPm5CMOiUicSHV6SlAQU9a5rQIDAQABAoICACf0/LA/PWq1U2/MHuNwTu8f
    DZ+fBJ4ILHPQKGChm3vDeyzTU1jWKEXQcA3p042hIcJ73aZ47jaK0oJNU7xXeZEB
    VxbPLzDNPrYIbzOMQ8w5IpaEIJTSdgM7wfPpuILOu0RPXbsauoQosmHSQ2NthUpb
    m5S07WWg42lWLtjPZApDbGKJOAvGlt4wXOf9RoHnBByU/bt7hVv2vEY5SL7DZWXV
    Y/5AafWR6FwtcxYHBB9AiOpfjX9S+2Xj7j1IuTirVtmS38FgHxVpOzjz7ekgtopc
    KlyRqtQJwl6jIQ8Tirps+CD/v+K6NacG01sVnG04TEXJ1gNYby2pZ/MFD8w2U4V5
    Q2DKKRw4uOfzpeTYU2RhIme7fRvasNGoCmBevH3iykqDOHy0l+Os4ZKA1LRybukC
    aby+hhPmtV032pJhXcJ1L8hgKmre64h3e+3MzUXT2JHAcS1sht/HHl5hj7W5PQJk
    BjFo5Jlxc8YdIbudRJwduXg62G489bMhsyahGCYaF2W9gITqhYPFovShYmhHme8f
    QeTx1EsD1jFq1JR+JlPpYmoYtbaqqeJWIOGNEBF4jigC3XRK3Dbm49fuKPiEQAVH
    GFh08q1RnpG+yWlANosJUq7ednyFtGMvuMw0yMCZhTkDnd0AzLT6q+/tIEDW6sl1
    IJUR0POG5GTrfHBDWCL7AoIBAQD0JGQ4QBNCclSf7CNne2c94tJwcc4YneBfSD7B
    FNo1CS770IoZs6KQr0JDOy+qiTnEiG66R/kgA4m/kIKVTm9hEM8VFTvfes5brG/F
    qGPPvddIgEcbcSRSIFN+D/W8kVuNhqh/swpfCrG5EIOiI3EAkh0h4yk7+mPS3Gd9
    MnoBESl3o7qbZKdWfSoU5maFisPmwt/hRxsPN3DQszqiMaNZCONG/dtEm9yMwWph
    YGPuz6fSkOgs0a6xfk7CLPZziUjSaCO3HypYt6QQgKBRY8FOzYJa1sMLpU9EvOhe
    r/azI9+f0iQK2jF1WHDERHsy7FCzhHpYmRWD0GbbCbvBOBJDAoIBAQDxbM5Ybjk2
    pfgFnKyXwQe3pY+VlGokUlv1Fll4TcqKP7QYXvuBPN9Lyhq7R2oo+IHMWJlJ2zK1
    88VJ6j+Sh1yc6alqlRdRv1HPpHFIZpnH/eiJsYUrk/sbQUNwvUO4fbyEiwpWRMl4
    r0M14n4QC54dFFAE7GMSKQgCbyRHusxkeYvybXRnRokHfgkVLg9to5ccbA/n3/li
    5DKCmOhuxJGR8ZjKiqLnP3ZdZdso5hLu0tzkCaUShX01QqNewpppeUtEIAWezbAz
    blEXzLR8QA4Y9CFQTwoeq+KxOT+RdXlQvaMMPeQ+hsgiyXQsBBWx755iitWixPJf
    lWcrOTxv8p1PAoIBAQCvhd5bpo1yLxpyI2ZMxqayEnmzB87hWdfvCNS9Ig3DJYgW
    2JYA5moQ1T+xcELTu3bBukjJOmd8Qa7t/6oyR8LBqUEIakyyXeswc2ekVmzz9Qtq
    /3af3xb6yGzebAEDAgotVMudi44ASIL/h0Tr88kRXPr+2v9RNLJB7d2lX/3g+IK0
    lgzaHWJFRxVTE1ZP2jT/mck1gFaO+Q/tq32TEFbc8wvbhTT4PYox0/h0a8VM8xQ3
    yaByYInU5/cdmQ/SfrfRNbe/tvNN9zFIAAHCohJfYla+kjqGC+JSi/IP6ThXEIp8
    r6rj9nyqXdws7wMX2FgoyCzht6WFL/ZSscu/nV1bAoIBAAGAw+gZB5InhlvClfB7
    6yhhh3tO6TpAqQHlmbj+AvzJWL2uGbK8RkeagoAX+bk3ktdK1el3y+EGG3xSUQMA
    hLsVWVCojPSdVE0OoQXqXZq5IfF5gXK8ARwyU9En3HwRjFLm6rGOzBJMRQbY2iAP
    cnSL49OkBRnf14TsXDV2HD+j4hMoS0k5TzEUv8m5966fDhnHMnInGs5azVWyzf+i
    iaV285SPOGRoKLx8HdkrVYLXHTjuNnDfE+B5AbtdSsjNUIKkEGTksuwfC7IyPA1p
    +Kx/GJX/Z/i46ThhOtwU9yRhidpRqFIbVLOivW5ouBnbfAjxBFN3Fmsx6uqB+LZZ
    tFECggEAZEc8Lp19uieVB/XD1fMIUFamd9jmx5aJyhxTo0sLJ8ItSB3mjZguvRYu
    JpnZ/Wwt0l8vfVzsqnRmsysdLYDXeFAuvFC3dC6afGiBFemrhJRTgK0FFsLKgt5s
    BR7uJuUh/uHz+Py4D5tpDXySw/MYEkBNl4LCMXhI3xQDS5273yFw5wxOLiL/WiaB
    hDTgLi4V2tGJ2lsd2JDCLxa6cuH5tymDcExfExsL+4mK6SGW+o7f6hvTVd6+AWIW
    5chz5e1v9/JRyaQUxGd0BDYPUJrumkhgR5QfdlGHYDmYcaW7Wx4TOOS54oH4ulUG
    +hID/9vYfFr2W1CI4zxu2AxID9hXLw==
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx-cm3
