apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
  name: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.redisData.size | default "5Gi" }}
{{- with .Values.persistence.redisData.storageClass }}
  storageClassName: {{ . }}
{{- end }}